apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-database
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: SecretStore
  target:
    name: backend-database
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: postgresql-credentials
        property: host
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgresql-credentials
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgresql-credentials
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgresql-credentials
        property: database
